version: "3.7"
services:
  surittec-db:
    container_name: ais-db
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: movie
      POSTGRES_USER: ais
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - ais-db
    depends_on:
      - ais-db
